env:
  - CXX=g++-4.8
sudo: required
language: node_js
services:
  - docker
node_js:
  - "8"
before_script:
  - echo "no code!"
  #create local bin directory
  - mkdir -p ~/.local/bin
  #install aws-cli
  - pip install --user awscli==1.14.39  # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  # install jq
  - curl -sSL -o ~/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/.local/bin/jq
  # install ecs-deploy (in work version)
  - curl https://raw.githubusercontent.com/kakakakakku/ecs-deploy/675e0e064bc20ad81634efdfe41d802fbe3c30e3/ecs-deploy | sudo tee -a ~/.local/bin/ecs-deploy
  - sudo chmod +x ~/.local/bin/ecs-deploy
  #ecr-login
  - eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
script:
  - echo "no tests!" # put your normal testing scripts here
  - docker build -t $TASK .
deploy:
  provider: script
  script: bash deploy_v2.sh
  on:
    tags: true
    all_branches: false
    condition: "$TRAVIS_TAG =~ ^([0-9]+).([0-9]+).([0-9]+).*$"
