env:
  - CXX=g++-4.8
sudo: required
language: node_js
services:
  - docker
node_js:
  - "8"
before_script:
  - echo "no code!"
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
script:
  - echo "no tests!" # put your normal testing scripts here
  - docker build -t sample-app .
deploy:
  provider: script
  script: bash deploy.sh
  on:
    tags: true
    all_branches: false
    condition: "$TRAVIS_TAG =~ ^([0-9]+).([0-9]+).([0-9]+).*$"
